import = [
    "colors/solarized.toml"
    #"colors/everforest.toml"
    #"colors/kanagawa.toml"
]

[font]
size = 12.0

[font.bold]
family = "Ubuntu Mono"
style = "Bold"

[font.bold_italic]
family = "Ubuntu Mono"
style = "Bold Italic"

[font.italic]
family = "Ubuntu Mono"
style = "Italic"

[font.normal]
family = "Ubuntu Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[window]
resize_increments = true
